os:
- windows
- linux
- osx
language: node_js
node_js:
- '12'
install:
- npm install -g gulp-cli
script:
- 
- cd labiba-transformer
- npm install --no-optional
- webpack
- 
- cd ..
- cd labiba-parser
- npm install
- npm install gulp
- gulp build
- 
- cd ..
- cd labiba-ide
- npm install
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run build-win          ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then npm run build-linux          ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm run build-mac          ; fi
deploy:
  provider: releases
  api_key:
    secure: d9jqP/VoM3Ti0AYBe8SuEzRb5Rfi2Iy0iXTEUTa4+r0ft/PPFm4LWyT4brlBlZMDJNJ1KIQ5XKvuF+ZlIjc9/pzGQ1OtXy6HziXuVUey9rEAil8nrfOKn3bQ8tqqIOpSkcQnQLWP74NbfqMWu4DQRmLaGLM73rTt7KX8shj6+pbRDetXMYdLHYOeqLBpjNc3xjwy4BKv/EV6POzNLABEH96MWkWk4tG4c8lk4CE12bAR5YH9dv2IUhhDN2JQyzzchHiUm5N6Fz2ohLlHpWB1Yk5Wy/F56rzhEqKomRKDVNOBO0wT85LvLWZqJxnwD4BxWTrvOps/X38C/EZ0P37ya2eDOBLp7wjaiiuxSXUXZmvSEqafqsorecJtEgcI/1ZQHZZlxTGG8EHBTSdLGg7SL5czotkR+c09UVGDGusrjBnSNiYXPCa8r6cmrNWsRvJz2FzfVu0CNGxwbkxXwLEU7lD2KD2liwk6U1+jLI2xeEVbZOfkG+rbqiS7WxlV/ZycQ6swN4SEZKodpa7Kh1I7KQjwvXO5YMb/ZSLN/0zToSORTYAT03tHpWFUrHlNE/d8Vfbmm3Ql3l8ibVBtRkR1gNvsrYu96v/3UO/bgXE27iCL0M24GkmaLTo/Kt+HPR8cA/LXZnAbPG3ab3yPbE076rANEDokzUr5uoN0FHyLmE0=
  file:
    - ./dist/Labiba.Setup.exe
    - dist/Labiba IDE 1.0.8.AppImage
    - dist/Labiba IDE-1.0.8-mac.zip
  skip_cleanup: true
  on:
    repo: fakoua/labiba
