language: node_js
node_js:
    - "12"
install:
  - npm install -g gulp-cli
script:
  - # ======== labiba-transformer
  - cd labiba-transformer
  - npm install --no-optional
  - webpack
  - # ======== labiba-parser
  - cd ..
  - cd labiba-parser
  - npm install
  - npm install gulp
  - gulp build
  - # ======== labiba-ide
  - cd ..
  - cd labiba-ide
  - npm install
  - npm run build-win
  - npm run build-linux
  - npm run build-mac
